/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.docs.assignment.student.model.impl;

import com.docs.assignment.student.model.Events;
import com.docs.assignment.student.model.EventsModel;
import com.docs.assignment.student.model.EventsSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Events service. Represents a row in the &quot;Student_Events&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EventsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventsImpl
 * @generated
 */
@JSON(strict = true)
public class EventsModelImpl
	extends BaseModelImpl<Events> implements EventsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a events model instance should use the <code>Events</code> interface instead.
	 */
	public static final String TABLE_NAME = "Student_Events";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"eventId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"eventName", Types.VARCHAR}, {"eventDescription", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("eventName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Student_Events (uuid_ VARCHAR(75) null,eventId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,eventName VARCHAR(75) null,eventDescription VARCHAR(75) null,startDate DATE null,endDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Student_Events";

	public static final String ORDER_BY_JPQL = " ORDER BY events.eventId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Student_Events.eventId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long EVENTID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Events toModel(EventsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Events model = new EventsImpl();

		model.setUuid(soapModel.getUuid());
		model.setEventId(soapModel.getEventId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEventName(soapModel.getEventName());
		model.setEventDescription(soapModel.getEventDescription());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Events> toModels(EventsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Events> models = new ArrayList<Events>(soapModels.length);

		for (EventsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EventsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Events.class;
	}

	@Override
	public String getModelClassName() {
		return Events.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Events, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Events, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Events, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Events)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Events, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Events, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Events)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Events, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Events, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Events>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Events.class.getClassLoader(), Events.class, ModelWrapper.class);

		try {
			Constructor<Events> constructor =
				(Constructor<Events>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Events, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Events, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Events, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Events, Object>>();
		Map<String, BiConsumer<Events, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Events, ?>>();

		attributeGetterFunctions.put("uuid", Events::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Events, String>)Events::setUuid);
		attributeGetterFunctions.put("eventId", Events::getEventId);
		attributeSetterBiConsumers.put(
			"eventId", (BiConsumer<Events, Long>)Events::setEventId);
		attributeGetterFunctions.put("groupId", Events::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Events, Long>)Events::setGroupId);
		attributeGetterFunctions.put("companyId", Events::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Events, Long>)Events::setCompanyId);
		attributeGetterFunctions.put("userId", Events::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Events, Long>)Events::setUserId);
		attributeGetterFunctions.put("userName", Events::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Events, String>)Events::setUserName);
		attributeGetterFunctions.put("createDate", Events::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Events, Date>)Events::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Events::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Events, Date>)Events::setModifiedDate);
		attributeGetterFunctions.put("eventName", Events::getEventName);
		attributeSetterBiConsumers.put(
			"eventName", (BiConsumer<Events, String>)Events::setEventName);
		attributeGetterFunctions.put(
			"eventDescription", Events::getEventDescription);
		attributeSetterBiConsumers.put(
			"eventDescription",
			(BiConsumer<Events, String>)Events::setEventDescription);
		attributeGetterFunctions.put("startDate", Events::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate", (BiConsumer<Events, Date>)Events::setStartDate);
		attributeGetterFunctions.put("endDate", Events::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate", (BiConsumer<Events, Date>)Events::setEndDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEventId() {
		return _eventId;
	}

	@Override
	public void setEventId(long eventId) {
		_eventId = eventId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEventName() {
		if (_eventName == null) {
			return "";
		}
		else {
			return _eventName;
		}
	}

	@Override
	public void setEventName(String eventName) {
		_eventName = eventName;
	}

	@JSON
	@Override
	public String getEventDescription() {
		if (_eventDescription == null) {
			return "";
		}
		else {
			return _eventDescription;
		}
	}

	@Override
	public void setEventDescription(String eventDescription) {
		_eventDescription = eventDescription;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Events.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Events.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Events toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Events>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventsImpl eventsImpl = new EventsImpl();

		eventsImpl.setUuid(getUuid());
		eventsImpl.setEventId(getEventId());
		eventsImpl.setGroupId(getGroupId());
		eventsImpl.setCompanyId(getCompanyId());
		eventsImpl.setUserId(getUserId());
		eventsImpl.setUserName(getUserName());
		eventsImpl.setCreateDate(getCreateDate());
		eventsImpl.setModifiedDate(getModifiedDate());
		eventsImpl.setEventName(getEventName());
		eventsImpl.setEventDescription(getEventDescription());
		eventsImpl.setStartDate(getStartDate());
		eventsImpl.setEndDate(getEndDate());

		eventsImpl.resetOriginalValues();

		return eventsImpl;
	}

	@Override
	public int compareTo(Events events) {
		long primaryKey = events.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Events)) {
			return false;
		}

		Events events = (Events)obj;

		long primaryKey = events.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EventsModelImpl eventsModelImpl = this;

		eventsModelImpl._originalUuid = eventsModelImpl._uuid;

		eventsModelImpl._originalGroupId = eventsModelImpl._groupId;

		eventsModelImpl._setOriginalGroupId = false;

		eventsModelImpl._originalCompanyId = eventsModelImpl._companyId;

		eventsModelImpl._setOriginalCompanyId = false;

		eventsModelImpl._setModifiedDate = false;

		eventsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Events> toCacheModel() {
		EventsCacheModel eventsCacheModel = new EventsCacheModel();

		eventsCacheModel.uuid = getUuid();

		String uuid = eventsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eventsCacheModel.uuid = null;
		}

		eventsCacheModel.eventId = getEventId();

		eventsCacheModel.groupId = getGroupId();

		eventsCacheModel.companyId = getCompanyId();

		eventsCacheModel.userId = getUserId();

		eventsCacheModel.userName = getUserName();

		String userName = eventsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			eventsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			eventsCacheModel.createDate = createDate.getTime();
		}
		else {
			eventsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			eventsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			eventsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		eventsCacheModel.eventName = getEventName();

		String eventName = eventsCacheModel.eventName;

		if ((eventName != null) && (eventName.length() == 0)) {
			eventsCacheModel.eventName = null;
		}

		eventsCacheModel.eventDescription = getEventDescription();

		String eventDescription = eventsCacheModel.eventDescription;

		if ((eventDescription != null) && (eventDescription.length() == 0)) {
			eventsCacheModel.eventDescription = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			eventsCacheModel.startDate = startDate.getTime();
		}
		else {
			eventsCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			eventsCacheModel.endDate = endDate.getTime();
		}
		else {
			eventsCacheModel.endDate = Long.MIN_VALUE;
		}

		return eventsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Events, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Events, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Events, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Events)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Events, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Events, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Events, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Events)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Events>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _eventId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _eventName;
	private String _eventDescription;
	private Date _startDate;
	private Date _endDate;
	private long _columnBitmask;
	private Events _escapedModel;

}